"""Create student system profiles table

Revision ID: dc9aed190fdb
Revises: 
Create Date: 2025-08-15 00:04:33.137506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9aed190fdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_system_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('study_style', sa.Enum('VISUAL', 'AUDITORY', 'KINESTHETIC', 'MIXED', name='studystyle'), nullable=False),
    sa.Column('preferred_times', sa.JSON(), nullable=True),
    sa.Column('tools_connected', sa.JSON(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_system_profiles_id'), 'student_system_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_student_system_profiles_user_id'), 'student_system_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_system_profiles_user_id'), table_name='student_system_profiles')
    op.drop_index(op.f('ix_student_system_profiles_id'), table_name='student_system_profiles')
    op.drop_table('student_system_profiles')
    # ### end Alembic commands ###
